name: Deploy

on:
  push:
    tags:
      - '*' # Запуск при пуше тегов

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Настройка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'

      # Шаг 2: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 3: Сборка проекта
      - name: Build project
        run: npm run build

      # Шаг 4: Передача файлов для деплоя
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Шаг 1: Скачивание собранного проекта
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
